# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of nod
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Update Github Pages Project Site
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          path: app-build
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci -g pnpm@^8
      - run: cd app-build
      - run: pnpm ci
      - run: pnpm run build --if-present
      - run: cd ..
      - uses: actions/checkout@v3
        with:
          ref: github-page
          path: app-page
      - run: cp ./app-build/dist ./app-page
      - run: git add .
      - run: git commit -m "update"
      - run: git push
